# Components prefixed CB are for keras callback hyperparamer settings

CB_tb: &TB
  # tensorboard
  nickname: tb
  class_name: TensorBoard
  kwargs: {log_dir: ./tensorboard, profile_batch: 0}

CB_es: &ES
  # Early stopping
  nickname: es
  class_name: EarlyStopping
  kwargs: {monitor: val_dice, min_delta: 0, patience: 200, verbose: 1, mode: max}

CB_mcp: &MCP
  # Model checkpoint
  nickname: mcp
  class_name: ModelCheckpoint
  kwargs: {filepath: './model/@epoch_{epoch:02d}_val_dice_{val_dice:.5f}.h5',
    monitor: val_dice, save_best_only: false, save_weights_only: true, verbose: 1,
    mode: max}

CB_timer: &TIMER
  # Train timer callback
  nickname: timer
  class_name: TrainTimer
  pass_logger: true
  kwargs: {verbose: true}

CB_csv: &CSV
  # keras.CSVLogger
  nickname: csv
  class_name: CSVLogger
  kwargs: {filename: ./logs/training.csv, separator: ',', append: true}

datasets:
  # Add dataset IDs --> relative paths here

  #### Training datasets

  # NSRR data (up to 2022)
  # abc: dataset_configurations/abc.yaml
  ccshs: dataset_configurations/ccshs.yaml
  # cfs: dataset_configurations/cfs.yaml
  # chat: dataset_configurations/chat.yaml
  # homepap: dataset_configurations/homepap.yaml
  # mesa: dataset_configurations/mesa.yaml
  # mros: dataset_configurations/mros.yaml
  # shhs: dataset_configurations/shhs.yaml
  # sof: dataset_configurations/sof.yaml

  #  # NSRR data (to date)
  #  apoe: dataset_configurations/apoe.yaml
  #  apples: dataset_configurations/apples.yaml
  #  mnc_cnc: dataset_configurations/mnc_cnc.yaml
  #  mnc_dhc: dataset_configurations/mnc_dhc.yaml
  #  mnc_ssc: dataset_configurations/mnc_ssc.yaml
  #  msp: dataset_configurations/msp.yaml
  #  nchsdb: dataset_configurations/nchsdb.yaml
  #  wsc: dataset_configurations/wsc.yaml

  #  # External DB
  #  dcsm: dataset_configurations/dcsm.yaml
  #  sedf_sc: dataset_configurations/sedf_sc.yaml
  #  sedf_st: dataset_configurations/sedf_st.yaml
  #  phys: dataset_configurations/phys.yaml

  #### Testing datasets

  #  # NSRR data
  #  stages: dataset_configurations/stages.yaml

  #  Inselspital data
  #  bsdb: dataset_configurations/stages.yaml

  # isruc_sg1: dataset_configurations/isruc_sg1.yaml
  # isruc_sg2: dataset_configurations/isruc_sg2.yaml
  # isruc_sg3: dataset_configurations/isruc_sg3.yaml
  # svuh: dataset_configurations/svuh.yaml
  # dod_o: dataset_configurations/dod_o.yaml
  # dod_h: dataset_configurations/dod_h.yaml

build:
  #
  # Hyperparameters passed to the __init__ method
  #
  model_class_name: LSeqSleepNet
  # input
  freq_bins: 129  #ndim
  time_bins: 29  #frame_seq_len
  n_channels: 2
  nsubseq: 20
  # model
  # filterbank
  nfilter: 32
  nfft: 256
  samplerate: 100
  lowfreq: 0
  highfreq: 50
  # epoch encoding
  nhidden_epoch: 64
  lstm_nlayer_epoch: 1
  # attention
  attention_size: 64
  # dual sequence encoder
  nhidden_seq: 64
  lstm_nlayer_seq: 1
  dual_rnn_blocks: 1
  # params for the whole model
  l2_reg_lambda: 0.0001
  batch_shape: [64, 200, 29, 129, 2]
  dropout_rnn: 0.9
  # used also for fc output, as reported in config of the original repo
  fc_size: 512
  n_classes: 5

augmenters:
  # On-the-fly augmentation
  [{cls_name: RegionalErase, kwargs: {min_region_fraction: 0.001, max_region_fraction: 0.33, log_sample: true,
      apply_prob: 0.1}}, {cls_name: ChannelDropout, kwargs: {drop_fraction: 0.5, apply_prob: 0.1}}]

fit:
  # Hyperparameters passed to the Trainer object
  balanced_sampling: true
  use_multiprocessing: false
  get_spectrogram: replace
  channel_mixture: false
  margin: 100

  # Loss function
  loss: [SparseCategoricalCrossentropy]
  # reduction: none
  metrics: [SparseCategoricalAccuracy]

  # Ignore 'out-of-bounds' classes in loss computation (e.g. to ignore 'UNKNOWN'/'MOVEMENT' other rare classes)
  # Comment out or set to Null/False to not ignore any classes
  ignore_out_of_bounds_classes: True

  # Optimization
  batch_size: 64
  n_epochs: 12000
  verbose: true
  optimizer: Adam
  optimizer_kwargs: {learning_rate: 1.0e-04, amsgrad: false, weight_decay: 0.0, beta_1: 0.9,
    beta_2: 0.999, epsilon: 1.0e-7}

  # Callbacks
  callbacks: [*TB, *MCP, *TIMER, *CSV, *ES]